# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Hello' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
 # 'node_modules'目录一般位于根目录中
  # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # 这个模块是用于调试功能的
    'RCTImage',
    # 在这里继续添加你所需要的模块
  ]
  # 如果你的RN版本 >= 0.42.0，请加入下面这行
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Pods for Hello

  target 'Hello-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HelloTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Hello-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Hello-tvOS

  target 'Hello-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
